function crossplot(snr)

close all;

set(groot','defaulttextinterpreter','latex');
set(groot, 'defaultAxesTickLabelInterpreter','latex'); 
set(groot, 'defaultLegendInterpreter','latex');

set(gcf,'units','pixels','position',[500,1000,1200,1200]);
set(gcf,'paperunits','centimeters','paperposition',[1,5,10,10]);
set(gcf,'color',[1,1,1]);
set(gca,'position',[0,0,1,1],'visible','off');
set(gca,'xlim',[0,1],'ylim',[0,1]);
ax0 = gca;

%******* figures *************

ymax = 2;
txt = 1;
fsize = 28;
cbar = 0;

ax(1)=axes('position',[0.1,0.1,0.75,0.75]);
hold on; box on;
set(gca,'layer','top');
set(gca,'xtick',[0:0.2:1],'xticklabel',[0:0.2:1]);
set(gca,'ytick',[0:1:2],'yticklabel',[0:1:2]);
if txt == 0,
    set(gca,'xticklabel',[],'yticklabel',[]);
end;
set(gca,'xlim',[0,1],'ylim',[0,ymax]);
set(gca,'fontsize',fsize);
if txt,
    xlabel('Ice cover fraction since 1 Ma');
    ylabel('Erosion since 1 Ma (m)'); %check Ero below, and corresponding E in compile_results
end

%load compiled results
% -- generated by compile_results.m
% load ..//models/SGreenland/compiled_results_.mat
load models/MDML/compiled_results_Temp2.mat

bvals = linspace(0,1,40);
zvals = linspace(0,ymax+1,40);
edges{1} = zvals(:);
edges{2} = bvals(:);

title(sample{snr}.name)

%add erosion
Ero = sample{snr}.E1(:);
    
%add d18O
burial = sample{snr}.b1My(:)/1e6;
    
N = hist3([Ero(:),burial(:)],'Edges',edges);
N = N/max(N(:));
[X,Y] = meshgrid(bvals,zvals);

axes(ax(1));
hold on; box on;
cvals = linspace(-3,0,100);
contourf(X,Y,log10(N+1e-6),cvals,'linestyle','none');
caxis([-3,0]);


if cbar,
    cb = colorbar;
    set(cb,'fontsize',fsize-4);
    set(cb,'position',[0.87,0.1,0.03,0.3],'ytick',[-2,-1,0],'xticklabel',[0.01,0.10,1.00],'ticklabelinterpreter','latex');
    if txt == 0, set(cb,'xticklabel',[]); 
    else, ylabel(cb,'Normalized P','interpreter','latex');
    end;
end;



mname = ['crossplot_',num2str(snr),'_MDML1.tif'];
frame = getframe(gcf);
im = frame2im(frame); 
[imind,cm] = rgb2ind(im,256); 
imwrite(imind,cm,mname,'tiff');

set(groot','defaulttextinterpreter','default');
set(groot, 'defaultAxesTickLabelInterpreter','default'); 
set(groot, 'defaultLegendInterpreter','default');
